# Generated by Django 4.0.4 on 2022-06-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=30)),
                ('nb_pieces', models.IntegerField()),
                ('date_dispo', models.DateField()),
                ('prix_mise_vente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=7)),
                ('type', models.IntegerField(choices=[(0, 'Neuf'), (1, 'Tb Etat'), (2, 'B Etat'), (3, 'Mauvais Etat')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to='agence.client')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agence.logement')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_commission', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.client')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.logement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visite',
            constraint=models.UniqueConstraint(fields=('client', 'logement', 'date_visite'), name='visite_Unique'),
        ),
        migrations.AddField(
            model_name='vente',
            name='client_acheteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.client'),
        ),
    ]
