# Generated by Django 4.0.4 on 2022-06-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_logement_vente_visite_visite_visite_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='etat',
            field=models.IntegerField(choices=[(0, 'Neuf'), (1, 'Tres bon etat'), (2, 'Bon etat'), (3, 'Mauvais etat')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logement',
            name='type',
            field=models.IntegerField(choices=[(0, 'Appartement'), (1, 'Maison'), (2, 'Local')]),
        ),
    ]
